name: relationship_os

description: Relationship OS Flutter client
publish_to: 'none'
version: 0.8.6+15

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
